// AI Control System — chat front door for the shared decision engine.
// Input: { message: string, history?: [{role, content}], agentId? }
//
// TWO MODES:
//  1) The message describes a concrete proposed AI action -> extract
//     { action_type, provider, description, params } with structured output and
//     hand it to the control-engine function, which owns ALL scoring, the
//     Allow/Modify/Block/Deferred verdict, real execution and the
//     agent_decisions logging. No decision logic is duplicated here.
//  2) Anything else -> normal conversational reply.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { buildCapabilityBlock } from "../_shared/capability-registry.ts";
import { pickAiGateway, callAiGateway } from "../_shared/ai-gateway.ts";
import { resolveAccountScope } from "../_shared/account-scope.ts";
import { evaluateExternalText } from "../_shared/outer-control-text-review.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

// Structured extraction contract — mirrors control-engine's input shape.
const EXTRACT_TOOL = {
  type: "function",
  function: {
    name: "review_action",
    description:
      "Call ONLY when the user is describing a concrete proposed AI action to review. " +
      "Extracts the action so the Control Engine can assess it.",
    parameters: {
      type: "object",
      additionalProperties: false,
      properties: {
        action_type: {
          type: "string",
          description:
            "Canonical tool kind if you can tell (send_email, reply_email, create_doc, edit_doc, " +
            "create_sheet, edit_sheet, create_calendar_event, slack_post_message, notion_create_page, " +
            "notion_update_page, canva_create_design, canva_create_folder, shopify_create_draft_order, " +
            "shopify_update_product, figma_post_comment, figma_create_dev_resource), else a short snake_case name.",
        },
        provider: {
          type: "string",
          description: "Gmail, Slack, Notion, Shopify, Canva, Figma, Google Docs, Google Sheets, Google Calendar, or 'unknown'.",
        },
        description: { type: "string", description: "Plain-language statement of what the user intends this action to do." },
        params: {
          type: "object",
          additionalProperties: true,
          description: "Concrete parameters mentioned by the user (channel, text, recipient, subject, product id, price...). Empty object if none.",
        },
      },
      required: ["action_type", "provider", "description", "params"],
    },
  },
};

// Problem 4 (Control System cannot clean general external text, 2026-10-08):
// Outer Control's own text-review gate (evaluateExternalText, Blueprint
// task #3) already evaluates and repairs a piece of EXTERNAL AI text
// against this exact account's hard/safety rules -- kill switches, hard
// rules, then the safety-rules scan, with real redaction when possible.
// It's already live for agent-runtime's http_post tool and for Outer
// Control API callers. The chat front door just never offered it: its
// system prompt's two on-topic modes were "review a proposed ACTION" and
// "explain the Control System," so a user pasting "here's what ChatGPT
// said, can you check this" fell outside both and got redirected by the
// OFF-TOPIC branch as if it had nothing to do with this account's AI
// governance -- when checking an external AI's output against this
// account's own rules is literally what this system is for. No new
// repair/evaluation logic needed; this just gives the existing chat a
// second tool so it can reach the primitive that already exists.
const REVIEW_TEXT_TOOL = {
  type: "function",
  function: {
    name: "review_external_text",
    description:
      "Call ONLY when the user pastes or quotes text that was GENERATED BY AN EXTERNAL AI (ChatGPT, Claude, a " +
      "connected CRM bot, any AI besides this account's own Generator agents) and wants it checked, cleaned, or " +
      "verified against this account's rules. Do NOT call this for text the user wrote themselves, and do NOT " +
      "call review_action for this -- an external AI's text has no action_type/provider to extract.",
    parameters: {
      type: "object",
      additionalProperties: false,
      properties: {
        content: { type: "string", description: "The exact external AI text to review, copied verbatim from what the user pasted or quoted." },
        source_model: { type: "string", description: "Which AI produced this text, if the user said (e.g. 'ChatGPT', 'Claude', 'our CRM bot'), else 'unknown'." },
      },
      required: ["content", "source_model"],
    },
  },
};

function formatTextReviewReply(result: Awaited<ReturnType<typeof evaluateExternalText>>): string {
  const verdictLabel = { allow: "Allow", modify: "Modify", block: "Block", escalate: "Needs approval" }[result.verdict];
  const lines = [`**${verdictLabel}** — trust score ${result.trustScore}/100`, "", result.summary];
  if (result.verdict === "modify" && result.output) {
    lines.push("", "Cleaned version:", "```", result.output, "```");
  }
  if (result.matches.length) {
    lines.push("", `Matched: ${result.matches.map((m) => m.name).join(", ")}.`);
  }
  return lines.join("\n");
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    const gw = pickAiGateway();
    if (!gw) return json({ error: "Missing OPENAI_API_KEY (or LOVABLE_API_KEY)" }, 500);

    const authHeader = req.headers.get("Authorization") || "";
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );
    const token = authHeader.replace("Bearer ", "");
    const { data: userData } = await supabase.auth.getUser(token);
    const userId = userData?.user?.id;
    if (!userId) return json({ error: "Not authenticated" }, 401);

    const body = await req.json().catch(() => ({}));
    const message = String(body?.message || "").trim();
    const agentId: string | null = body?.agentId ? String(body.agentId) : null;
    const dryRun = body?.dry_run === true;
    if (!message) return json({ error: "message required" }, 400);

    // Was ALWAYS userId regardless of which account was selected via the
    // account switcher on the Control System page -- a delegated team
    // member's "review this action" chat silently reviewed/spent/executed
    // against THEIR OWN account instead of the one they were viewing.
    // control-engine independently resolves + re-verifies this same
    // account_id (never trusts this layer's resolution as authorization on
    // its own); resolving it here too so this function's OWN context
    // (recent decisions, connected integrations) matches the account the
    // decision itself will actually run against.
    const userClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const requestedAccountId = body?.account_id;
    const accountId = await resolveAccountScope(userClient, userId, requestedAccountId);
    if (!accountId) return json({ error: "forbidden", message: "You don't have owner access on that account." }, 403);

    // Recent decision history — lets the assistant explain past verdicts.
    const { data: recent } = await supabase
      .from("agent_decisions")
      .select("decision, reasoning, confidence_score, created_at")
      .eq("user_id", accountId)
      .order("created_at", { ascending: false })
      .limit(10);
    const historyBlock = (recent || []).length
      ? (recent as Record<string, unknown>[])
        .map((r) => `- ${r.created_at}: ${r.decision} (confidence ${r.confidence_score ?? "?"}) — ${String(r.reasoning || "").slice(0, 200)}`)
        .join("\n")
      : "(no decisions logged yet)";

    // Capability visibility — grounds "what can you actually do" answers in
    // the real capability registry instead of the model guessing or
    // over-claiming. Same source of truth agent-runtime uses to decide
    // whether a tool is genuinely offered.
    const { data: connsRows } = await supabase
      .from("agent_integrations")
      .select("provider")
      .eq("user_id", accountId)
      .eq("status", "connected");
    const connectedProviders = ((connsRows ?? []) as { provider: string }[]).map((c) => c.provider);
    const capabilityBlock = buildCapabilityBlock(connectedProviders);

    const priorTurns = Array.isArray(body?.history)
      ? (body.history as { role?: string; content?: string }[])
        .filter((m) => (m?.role === "user" || m?.role === "assistant") && typeof m.content === "string" && m.content.trim())
        .slice(-10)
        .map((m) => ({ role: m.role as "user" | "assistant", content: String(m.content).slice(0, 4000) }))
      : [];

    const res = await callAiGateway({
        model: gw.model,
        temperature: 0.3,
        messages: [
          {
            role: "system",
            content:
              "You are the AI Control System — a focused assistant for ONE topic: this account's AI governance " +
              "(reviewing proposed AI actions, reviewing/cleaning text an EXTERNAL AI produced, explaining " +
              "rules/decisions/incidents, and what this account's AI can actually do right now). You are not a " +
              "general-purpose assistant.\n\n" +
              "THREE MODES, for on-topic messages only:\n" +
              "1) If (and only if) the user is describing a concrete proposed AI action to review " +
              "(e.g. 'my agent wants to post to #general', 'should I let this run: email all customers'), " +
              "call the review_action tool with the action extracted faithfully. Do NOT judge it yourself — " +
              "the Control Engine does the intent, risk and fit checks. Never invent parameters the user didn't give.\n" +
              "2) If the user pastes or quotes text that an EXTERNAL AI produced (ChatGPT, Claude, a connected " +
              "CRM bot, anything besides this account's own Generator agents) and wants it checked, cleaned, or " +
              "verified against this account's rules, call the review_external_text tool with the exact text. " +
              "This is squarely on-topic -- checking an external AI's output against this account's own rules is " +
              "exactly what this system is for, not a request to redirect.\n" +
              "3) Otherwise, reply normally in plain text — answer questions about how the Control System works, " +
              "explain past decisions, or ask ONE clarifying question when intent is ambiguous. " +
              "Do NOT call either tool in this mode. If asked what you can actually do or verify right now, answer ONLY from " +
              "the CAPABILITY REGISTRY below — never guess or round up, and always say plainly which things need an account " +
              "connected first.\n\n" +
              "OFF-TOPIC MESSAGES: if the message has nothing to do with this account's AI governance -- general " +
              "knowledge questions, trivia, coding help unrelated to this product, creative writing, personal " +
              "advice, or anything else outside reviewing AI actions, reviewing external AI text, and explaining " +
              "this Control System -- do NOT answer it, even partially, and do NOT call either tool. Instead reply " +
              "with ONE short, friendly sentence redirecting back to what you actually do here, e.g.: \"That's " +
              "outside what I can help with here -- I'm focused on your AI's actions and rules. Want me to review " +
              "something your AI wants to do, check a response from an external AI, or explain a past decision?\" " +
              "Vary the wording naturally, but always steer back to this topic in a single sentence rather than " +
              "engaging with the off-topic request.\n\n" +
              "Always write in plain everyday language.\n\n" +
              "HOW YOU WORK (for explaining yourself): a proposed action is parsed, then the Control Engine scores intent match, " +
              "risk (low/medium/high) and business fit, weighs confidence (0-100) against a threshold, and returns one of four " +
              "verdicts — Allow, Modify, Block, or Deferred (not a fit). When a verdict is Allow and a real verified executor exists " +
              "for that tool, the action is actually carried out and verified; otherwise only the assessment happens. " +
              "Every verdict is logged to the shared decision history that agents also write to.\n\n" +
              `RECENT DECISION HISTORY:\n${historyBlock}` +
              `\n${capabilityBlock}`,
          },
          ...priorTurns,
          { role: "user", content: message },
        ],
        tools: [EXTRACT_TOOL, REVIEW_TEXT_TOOL],
        tool_choice: "auto",
    }, gw);

    if (res.status === 429) return json({ error: "rate_limited", message: "Too many requests right now — try again in a moment." }, 429);
    if (res.status === 402) return json({ error: "payment_required", message: "AI credits are exhausted. Add credits to continue." }, 402);
    if (!res.ok) return json({ error: "gateway_error", message: (await res.text()).slice(0, 400) }, 502);

    const data = await res.json();
    const msg = data?.choices?.[0]?.message;
    const call = msg?.tool_calls?.[0];
    let parsed: Record<string, unknown> = {};
    try { parsed = JSON.parse(call?.function?.arguments || "{}"); } catch { /* fall through */ }

    if (call?.function?.name === "review_external_text") {
      const content = String(parsed.content || "").slice(0, 8000);
      if (!content.trim()) {
        return json({ mode: "chat", reply: "I didn't catch the text to review — paste it and I'll check it against your rules." });
      }
      const result = await evaluateExternalText(supabase, {
        userId: accountId,
        agentId,
        apiKeyId: null,
        isTest: false,
        sourceModel: String(parsed.source_model || "unknown").slice(0, 80),
        content,
        origin: "external-api",
      });
      return json({ mode: "chat", reply: formatTextReviewReply(result) });
    }

    if (!parsed.action_type) {
      // Not an action to review — normal conversational reply.
      const reply = String(msg?.content || "").trim() ||
        "Could you tell me a bit more about what you'd like the AI to do?";
      return json({ mode: "chat", reply });
    }

    // ---- Hand off to the shared Control Engine ----------------------------
    const actionType = String(parsed.action_type);
    const provider = String(parsed.provider || "unknown");
    const description = String(parsed.description || message).slice(0, 2000);
    const params = (parsed.params && typeof parsed.params === "object") ? parsed.params : {};

    const engineRes = await fetch(`${Deno.env.get("SUPABASE_URL")}/functions/v1/control-engine`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
        apikey: Deno.env.get("SUPABASE_ANON_KEY") || "",
      },
      body: JSON.stringify({ action_type: actionType, provider, description, params, agentId, dry_run: dryRun, account_id: accountId }),
    });
    const engine = await engineRes.json().catch(() => ({}));
    if (!engineRes.ok || engine?.error) {
      return json(
        { error: engine?.error || "control_engine_error", message: engine?.message || "The Control Engine couldn't review that action." },
        engineRes.status === 200 ? 502 : engineRes.status,
      );
    }

    return json({ mode: "decision", description, params, ...engine });
  } catch (e) {
    return json({ error: "unexpected", message: String((e as Error)?.message || e) }, 500);
  }
});
