// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-agents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_agents_default = defineTool({
  name: "list_agents",
  title: "List NazAI agents",
  description: "List all NazAI AI agents owned by the signed-in user, including id, name, role, goal, status, autonomy, and schedule.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max agents to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("agents").select("id, name, slug, role, goal, status, autonomy, schedule_label, next_run_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { agents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-agent.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_agent_default = defineTool2({
  name: "get_agent",
  title: "Get NazAI agent",
  description: "Get the full manifest for a specific NazAI agent (system prompt, tools, triggers, guardrails, KPIs, UI spec).",
  inputSchema: {
    agent_id: z2.string().uuid().describe("The agent's UUID (from list_agents).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ agent_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("agents").select("*").eq("id", agent_id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Agent not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { agent: data }
    };
  }
});

// src/lib/mcp/tools/list-agent-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_agent_events_default = defineTool3({
  name: "list_agent_events",
  title: "List agent events",
  description: "List the most recent runtime events (reasoning, tool_call, tool_result, action, finished, error) for a NazAI agent.",
  inputSchema: {
    agent_id: z3.string().uuid().describe("The agent's UUID."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max events (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ agent_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("agent_events").select("id, run_id, kind, payload, created_at").eq("agent_id", agent_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List NazAI projects",
  description: "List the signed-in user's NazAI projects (generated websites and missions).",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max projects (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("projects").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/run-agent.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
var run_agent_default = defineTool5({
  name: "run_agent",
  title: "Run NazAI agent now",
  description: "Manually trigger a run of a NazAI agent against its connected business tools. Returns the run summary.",
  inputSchema: {
    agent_id: z5.string().uuid().describe("The agent's UUID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ agent_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const url = `${process.env.SUPABASE_URL}/functions/v1/agent-runtime`;
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`,
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY
      },
      body: JSON.stringify({ agentId: agent_id, trigger: "mcp" })
    });
    const text = await resp.text();
    if (!resp.ok)
      return { content: [{ type: "text", text: `Run failed (${resp.status}): ${text}` }], isError: true };
    let parsed = text;
    try {
      parsed = JSON.parse(text);
    } catch {
    }
    return {
      content: [{ type: "text", text: typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2) }],
      structuredContent: { result: parsed }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ekuodpaaiugzywfcmjeo";
var mcp_default = defineMcp({
  name: "nazai-mcp",
  title: "NazAI",
  version: "0.1.0",
  instructions: "Tools for NazAI, an AI-agent generator. Use `list_agents` to see the user's agents, `get_agent` for the full manifest, `list_agent_events` for recent runtime activity, `list_projects` for generated websites/missions, and `run_agent` to trigger a manual run.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_agents_default, get_agent_default, list_agent_events_default, list_projects_default, run_agent_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
